# Generated by Django 6.0.5 on 2026-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.CharField(max_length=5)),
                ('room_no', models.CharField(max_length=10)),
                ('room_owner', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=10)),
            ],
        ),
    ]
